EDITION_ID=plasma
DISPLAY_NAME=Influent Danenone Plasma
UPDATE_POLICY=automatic
DEFAULT_THEME=verdypor
PACKAGE_SET=plasma
APP_SET=home
FEATURE_SET=desktop,foundstore,hardware-controls,notifications,plasma-wayland,hyprland-advanced,calamares-branding
