EDITION_ID=developer
DISPLAY_NAME=Influent Danenone Developer
UPDATE_POLICY=fast
DEFAULT_THEME=dark
PACKAGE_SET=developer
APP_SET=developer
FEATURE_SET=desktop,foundstore,hardware-controls,notifications,compiler-toolchain,qt-development,python-development,node-development,debugging,containers
